### ISSUE TITLE
Invalid char in windows

### ISSUE THREAD

**Issue by AndreiTS** [react-component/resize-observer#213]
➤ YN0001: │ Error: While persisting /C:/Users/---/---/---/---/.yarn/cache/rc-resize-observer-npm-1.4.1-95fdc1562f-259067f09d.zip/node_modules/rc-resize-observer/ -> /C:/Users/---/---/---/---/node_modules/rc-resize-observer ENOENT: no such file or directory, mkdir 'C:\Users\---\---\---\---\node_modules\rc-resize-observer\dist\~demos\:id'

similar to: https://github.com/yarnpkg/berry/issues/4985

**Comment by varandej** [comment]
same here and haven't found the solution yet
force downgrading to 1.4.0 doesn't work cause something from antd still fetches it

btw, I'm sure the dist folder with the docs code shouldn't exist in the lib package :\

**Comment by msalsergey** [comment]
For a temporary solution, I added the `rc-resize-observer`: "1.4.0" to the resolution in package.json. Then, I ran the `yarn install` command.

**Comment by lyt8384** [comment]
Same problem

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/resize-observer/pull/214 , please reinstall node_modules after remove all lock files.
